### ISSUE TITLE
HDR support

### ISSUE THREAD

**Issue by EnricoMonese** [andydbc/unity-frosted-glass#3]
If anyone needs HDR support you can add `RenderTextureFormat.DefaultHDR` as a parameter to the `GetTemporaryRT` calls in `CommandBufferBlur.cs`

**Comment by DashW** [comment]
Why wouldn't you need HDR support?!

**Comment by omgitsraven** [comment]
I think the issue is more that some platforms don't *support* HDR.

I've actually been trying to come up with a patch to handle this automatically, but I can't figure out how to approach it: https://answers.unity.com/questions/1520753/how-to-determine-if-rendering-is-actually-hdr.html

**Comment by omgitsraven** [comment]
well, moments after I posted that, someone replied with a possible answer, so if it was someone here then thank you ;) I've got a pull request here https://github.com/andydbc/unity-frosted-glass/pull/9 that seems to work, although I haven't been totally able to test what happens in situations where HDR is not possible on the hardware. Feedback is welcome.

**Comment by omgitsraven** [comment]
and https://github.com/andydbc/unity-frosted-glass/pull/9 is accepted!
